# Generated by Django 3.2.4 on 2021-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('price', models.FloatField(max_length=50, verbose_name='price')),
            ],
        ),
    ]
