# Generated by Django 3.2.4 on 2021-12-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_store_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('price', models.FloatField(max_length=50, verbose_name='price')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.store')),
            ],
        ),
    ]
